package spring.jpa.foreign_keys;

import lombok.*;
import org.hibernate.Hibernate;

import jakarta.persistence.*;
import java.util.Objects;

import static jakarta.persistence.FetchType.LAZY;
import static jakarta.persistence.GenerationType.SEQUENCE;

@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name = "many2one")
class ManyToOneEntity extends AuditedEntity {
    @Id
    @GeneratedValue(strategy = SEQUENCE)
    Integer id;

    @ManyToOne(optional = false, fetch = LAZY)
    @ToString.Exclude
    OneToManyEntity parent;

    public int getParentIdMethod() {
        return getParent().getId();
    }

    public int getParentIdField1() {
        return getParent().id;
    }

    public int getParentIdField2() {
        return parent.id;
    }

    // Autogenerated equals() & hashCode() //
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        ManyToOneEntity that = (ManyToOneEntity) o;
        return id != null && Objects.equals(id, that.id);
    }
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
